version: '3.1'

services:

  spring-boot-docker-app:
    image: spring-boot-docker-app
    restart: always
    ports:
      - 8080:8080
    environment:
	POSTGRES_URL: "jdbc:postgresql://docker-postgres:5432/customer"
  docker-postgres:
    container_name: docker-postgres
    image: postgres
    restart: always
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
